"""PDF report generator.

REQ-FUNC-33, REQ-FUNC-34, REQ-FUNC-35, REQ-EXP-02:
Create a PDF summary, similarity histogram, and suspect pair table using reportlab.
"""

from __future__ import annotations

from datetime import datetime
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, Preformatted, SimpleDocTemplate, Spacer, Table, TableStyle


MAX_SUSPECT_PAIR_ROWS = 25
MAX_STUDENT_IMPACT_ROWS = 12


def _footer(canvas: Any, _doc: Any) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    footer_text = "Generated by Parallel Plagiarism Detector — Group 14, CSC344"
    canvas.drawString(0.75 * inch, 0.5 * inch, footer_text)
    canvas.drawRightString(7.75 * inch, 0.5 * inch, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def _histogram_text(results: dict[str, Any]) -> str:
    bins = [0] * 10
    for pair in results.get("pairs", []):
        similarity = float(pair.get("similarity", 0.0))
        index = min(9, int(similarity // 10))
        bins[index] += 1

    lines = ["Similarity Distribution"]
    for index, count in enumerate(bins):
        start = index * 10
        end = 100 if index == 9 else (index + 1) * 10
        bar = "#" * min(count, 40)
        lines.append(f"{start:02d}-{end:02d}% | {bar:<40} {count}")
    return "\n".join(lines)


def _risk_fill(risk_level: str) -> colors.Color:
    if risk_level == "high":
        return colors.HexColor("#FEE2E2")
    if risk_level == "medium":
        return colors.HexColor("#FEF3C7")
    return colors.HexColor("#DCFCE7")


def _copy_impact_score(match_count: int, average_similarity: float, max_similarity: float) -> float:
    score = (0.45 * average_similarity) + (0.4 * max_similarity) + min(15.0, match_count * 2.0)
    return round(min(100.0, score), 1)


def _impact_label(score: float, max_similarity: float) -> str:
    if score >= 85.0 or max_similarity >= 95.0:
        return "Immediate review"
    if score >= 70.0 or max_similarity >= 85.0:
        return "Detailed review"
    if score >= 50.0:
        return "Monitor"
    return "Low concern"


def _build_student_profiles(pairs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    profiles: dict[str, dict[str, Any]] = {}

    for pair in pairs:
        file_a = str(pair.get("fileA", "")).strip()
        file_b = str(pair.get("fileB", "")).strip()
        similarity = float(pair.get("similarity", 0.0))

        for current_file, other_file in ((file_a, file_b), (file_b, file_a)):
            if not current_file:
                continue

            profile = profiles.setdefault(
                current_file,
                {
                    "file": current_file,
                    "match_count": 0,
                    "total_similarity": 0.0,
                    "max_similarity": 0.0,
                    "top_match": "",
                    "top_match_similarity": 0.0,
                },
            )
            profile["match_count"] += 1
            profile["total_similarity"] += similarity
            if similarity > profile["max_similarity"]:
                profile["max_similarity"] = similarity
            if similarity >= profile["top_match_similarity"]:
                profile["top_match"] = other_file
                profile["top_match_similarity"] = similarity

    for profile in profiles.values():
        match_count = int(profile["match_count"])
        average_similarity = round(profile["total_similarity"] / max(1, match_count), 1)
        max_similarity = round(float(profile["max_similarity"]), 1)
        impact_score = _copy_impact_score(match_count, average_similarity, max_similarity)
        profile["average_similarity"] = average_similarity
        profile["max_similarity"] = max_similarity
        profile["impact_score"] = impact_score
        profile["recommendation"] = _impact_label(impact_score, max_similarity)

    ordered_profiles = sorted(
        profiles.values(),
        key=lambda item: (
            float(item["impact_score"]),
            float(item["max_similarity"]),
            int(item["match_count"]),
            str(item["file"]).lower(),
        ),
        reverse=True,
    )
    return ordered_profiles


def _teacher_summary_lines(stats: dict[str, Any], student_profiles: list[dict[str, Any]]) -> list[str]:
    files_processed = int(stats.get("filesProcessed", 0))
    total_pairs = int(stats.get("totalPairsFound", stats.get("candidatePairs", 0)))
    high_confidence = int(stats.get("highConfidenceMatches", 0))
    average_similarity = float(stats.get("averageSimilarity", 0.0))
    top_offender = str(stats.get("summary", {}).get("topOffender") or "")
    top_offender_count = int(stats.get("summary", {}).get("topOffenderMatchCount", 0) or 0)

    lines = [
        f"This batch reviewed {files_processed} files and found {total_pairs} suspect pairs.",
        f"Average pair similarity was {average_similarity:.1f}%, with {high_confidence} high-confidence matches requiring the closest review.",
    ]

    if top_offender:
        lines.append(
            f"Most involved submission: {top_offender} appears in {top_offender_count} suspect pair(s)."
        )

    if student_profiles:
        top_profile = student_profiles[0]
        lines.append(
            f"Highest copy-impact score: {top_profile['file']} at {top_profile['impact_score']:.1f}/100 ({top_profile['recommendation']})."
        )

    lines.append(
        f"Use the student impact table to assign marks quickly, then open the top {min(MAX_SUSPECT_PAIR_ROWS, len(student_profiles))} pair matches for detailed evidence."
    )
    return lines


def generate_pdf_report(results: dict[str, Any], settings: dict[str, Any] | None = None) -> bytes:
    """Render results into a PDF report and return the bytes."""

    settings = settings or {}
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        rightMargin=36,
        leftMargin=36,
        topMargin=48,
        bottomMargin=48,
        pageCompression=0,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "PlagDetTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=26,
        textColor=colors.HexColor("#0F172A"),
    )
    body_style = ParagraphStyle(
        "PlagDetBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
    )

    stats = results.get("stats", {})
    pairs = list(results.get("pairs", []))
    pairs.sort(key=lambda item: float(item.get("similarity", 0.0)), reverse=True)
    student_profiles = _build_student_profiles(pairs)
    displayed_pairs = pairs[:MAX_SUSPECT_PAIR_ROWS]

    story: list[Any] = []
    story.append(Paragraph("Plagiarism Detection Report", title_style))
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph(f"Date of generation: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", body_style))
    story.append(Paragraph(f"Language analyzed: {stats.get('language', 'unknown')}", body_style))
    story.append(Paragraph("Generated by Parallel Plagiarism Detector — Group 14, CSC344", body_style))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Teacher Summary", styles["Heading2"]))
    for line in _teacher_summary_lines(stats, student_profiles):
        story.append(Paragraph(line, body_style))
    story.append(Spacer(1, 0.15 * inch))

    summary_rows = [
        ["Total files processed", str(stats.get("filesProcessed", 0))],
        ["Total elapsed time (s)", f"{float(stats.get('totalElapsedTime', 0.0)):.3f}"],
        ["Suspect pairs found", str(int(stats.get('totalPairsFound', len(pairs))))],
        ["Pairs shown in report", str(len(displayed_pairs))],
        ["High-confidence matches", str(int(stats.get('highConfidenceMatches', 0)))],
        ["Average similarity", f"{float(stats.get('averageSimilarity', 0.0)):.1f}%"],
        ["Top involved submission", str(stats.get('summary', {}).get('topOffender') or "None")],
        ["Top submission match count", str(int(stats.get('summary', {}).get('topOffenderMatchCount', 0) or 0))],
        ["Similarity threshold", f"{float(settings.get('threshold', 85)):.1f}%"],
        ["K-gram size", str(settings.get("kGramSize", 5))],
        ["Signature length", str(settings.get("signatureLength", 100))],
        ["Bands", str(settings.get("bands", 20))],
        ["Speedup achieved", f"{float(stats.get('speedupAchieved', 0.0)):.2f}x"],
    ]
    summary_table = Table(summary_rows, colWidths=[2.4 * inch, 3.2 * inch])
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#DBEAFE")),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#0F172A")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("LEADING", (0, 0), (-1, -1), 12),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 0.25 * inch))

    if student_profiles:
        story.append(Paragraph("Student Copy Impact", styles["Heading2"]))
        impact_rows = [["File", "Matches", "Strongest Match", "Avg Similarity", "Impact Score", "Guidance"]]
        for profile in student_profiles[:MAX_STUDENT_IMPACT_ROWS]:
            strongest = profile["top_match"] or "-"
            if strongest != "-":
                strongest = f"{strongest} ({profile['top_match_similarity']:.1f}%)"
            impact_rows.append(
                [
                    profile["file"],
                    str(profile["match_count"]),
                    strongest,
                    f"{profile['average_similarity']:.1f}%",
                    f"{profile['impact_score']:.1f}/100",
                    profile["recommendation"],
                ]
            )

        impact_table = Table(
            impact_rows,
            colWidths=[1.7 * inch, 0.65 * inch, 2.15 * inch, 0.85 * inch, 0.8 * inch, 1.0 * inch],
            repeatRows=1,
        )
        impact_style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5E1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ]
        for row_index, profile in enumerate(student_profiles[:MAX_STUDENT_IMPACT_ROWS], start=1):
            score = float(profile["impact_score"])
            fill = colors.HexColor("#FEE2E2") if score >= 85 else colors.HexColor("#FEF3C7") if score >= 60 else colors.HexColor("#DCFCE7")
            impact_style.append(("BACKGROUND", (4, row_index), (4, row_index), fill))
        impact_table.setStyle(TableStyle(impact_style))
        story.append(impact_table)
        story.append(Paragraph("Higher impact scores indicate a file that appears repeatedly in suspicious pairs and deserves the most grading attention.", body_style))
        story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Similarity Distribution", styles["Heading2"]))
    story.append(Preformatted(_histogram_text(results), body_style))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Suspect Pairs", styles["Heading2"]))
    if displayed_pairs:
        table_data = [["#", "File A", "File B", "Similarity %", "Risk Level"]]
        for index, pair in enumerate(displayed_pairs, start=1):
            table_data.append(
                [
                    str(index),
                    str(pair.get("fileA", "")),
                    str(pair.get("fileB", "")),
                    f"{float(pair.get('similarity', 0.0)):.1f}%",
                    str(pair.get("riskLevel", "low")).title(),
                ]
            )

        pairs_table = Table(table_data, colWidths=[0.4 * inch, 2.35 * inch, 2.35 * inch, 0.9 * inch, 0.8 * inch], repeatRows=1)
        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1D4ED8")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5E1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        for row_index, pair in enumerate(displayed_pairs, start=1):
            risk_level = str(pair.get("riskLevel", "low")).lower()
            style_commands.append(("BACKGROUND", (0, row_index), (-1, row_index), _risk_fill(risk_level)))
        pairs_table.setStyle(TableStyle(style_commands))
        story.append(pairs_table)
        if len(pairs) > MAX_SUSPECT_PAIR_ROWS:
            story.append(Spacer(1, 0.1 * inch))
            story.append(
                Paragraph(
                    f"Only the top {MAX_SUSPECT_PAIR_ROWS} pairs are shown here to keep the report teacher-ready. The interactive results page contains the full ranked list.",
                    body_style,
                )
            )
    else:
        story.append(Paragraph("No suspect pairs met the configured threshold.", body_style))

    document.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()
